BINARY = exec
CC = gcc
CPPFLAGS = -I./include 
CFLAGS = -g -Wall 
LDFLAGS = -L./lib
LDLIBS = -lm

SRCS := $(wildcard *.c)
OBJS := $(patsubst %.c,%.o,$(SRCS))

all: $(BINARY)

$(BINARY): $(OBJS)
	$(CC) $(LDFLAGS) -o $@ $(OBJS) $(LDLIBS)

clean:
	rm -f $(OBJS) $(BINARY)
