BASENAME = haskell-yesod
CODEINPUTS = function-composition.hs\
	     types1.hs types2.hs types3.hs types4.hs types5.hs\
	     fibo.hs\
	     qsort.hs\
	     newtypes1.hs newtypes2.hs\
	     yesod.hs
DEPTH = ../../
include $(DEPTH)/latex-beamer.mk
