BASENAME = design-patterns
CODEDIR = code
CODEINPUTS = 1singleton.h 1singleton.cpp 1main.cpp\
	     2visitor.h 2visitor2.h 2visitor.cpp 2main.cpp\
	     3decorator.h 3decorator.cpp 3main.cpp
DEPTH = ../../
include $(DEPTH)/latex-beamer.mk
