#!/bin/bash
#
# An example hook script that is called after a successful
# commit is made.
#
# To enable this hook, make this file executable.

msg()
{
    echo "[post-receive]  $@"
}

log_dir=/home/git/hooks.log
clone_dir=/home/git/cdl-clone
pdf_dir=/home/cdl/www/2010/store/pdf/
repo_url=git@git.rosedu.org:cdl.git

echo "Hook cdl "`date` >> $log_dir
#rm $clone_dir -fr

#git clone $repo_url $clone_dir
cd $clone_dir

git pull &> /dev/null && git reset --hard > /dev/null && msg Updated cloned repository

cd $clone_dir 

for i in `find 2010 -name '*.tex'`;
do
	cd $clone_dir/`dirname $i`
	make &> /dev/null
done

cd $clone_dir
for i in `find 2010 -name '*.pdf'`;
do
	curs=`echo $i | cut -d/ -f 2`
	cp $i $pdf_dir/$curs"_"`basename $i`
done

