BINARY = exec
LDFLAGS = -L./lib
CC = gcc
CFLAGS = -g -Wall 
CPPFLAGS = -I./include 
LIBS = 

SRCS := $(wildcard *.c)
OBJS := $(patsubst %.c,%.o,$(SRCS))

all: $(BINARY)

$(BINARY): $(OBJS)
	$(CC) $(CFLAGS) $(CPPFLAGS) $(LDFLAGS) -o $@ $(OBJS) $(LIBS)

clean:
	rm -f $(OBJS) $(BINARY)
